name: azure-func-cd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch

      - name: az-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: prepare-package-folder
        run: |
          mkdir -m777 package

      - name: download-artifact
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob download -f ./package/function.zip --container-name releases --account-name botfuncstoragecicd83rj -n "${{ steps.branch.outputs.branch }}/build/function.zip"

      - name: deploy-azure-function
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd package
            echo "function.zip" > packagename.txt
            az storage file upload-batch --account-name botfuncstoragecicd83rj --destination bot-solgari-funccustom --source . --destination-path /data/SitePackages