name: azure-func-cd

on:
  workflow_dispatch:

jobs:
  execution:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch

      - name: az-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: download-artifact
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob download -f function.zip --container-name releases --account-name azurefuncreleases -n "${{ steps.branch.outputs.branch }}/build/function.zip"

      - name: deploy-azure-function
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp deployment source config-zip -g rusak-terraform-function-test-rg -n rusak-linux-function-app --src function.zip