name: azure-func-ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch

      - name: setup-node-js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: npm-dependencies-install
        run: npm ci

      - name: build-function
        run: npm run build

      - name: tests
        run: npm test
      
      - name: create-artifact
        run: |
          npm prune --production
          zip -r function.zip . --exclude @.funcignore --exclude .funcignore
      
      - name: az-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: upload-artifact
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --file function.zip --container-name releases --account-name botfuncstoragecicd83rj --name "${{ steps.branch.outputs.branch }}/build/function.zip" --overwrite true
            az storage blob upload --file function.zip --container-name releases --account-name botfuncstoragecicd83rj --name "${{ steps.branch.outputs.branch }}/${{ github.sha }}/function.zip" --overwrite true